### ISSUE TITLE
Season 6 Checklist

### ISSUE THREAD

**Issue by Blaylock1988** [GV-Server-Mods/GVK-Settings#317]
- [x] record test players
- [x] merge S6 branches into main and republish
- [x] Reset Voxels
- [x] Clear known steam IDs
- [x] Purge players in SE
- [x] Purge NPC factions
- [x] Delete Grid Backups
- [x] Delete Hangar
- [x] Delete Faction Hangar Storage
- [x] Delete MES sbcb5 files
- [x] Clear server logs
- [x] Clear clear mod content logs
- [x] Set up Safezones
- [x] Set MES bools to false
- [x] Clear and respawn all NPC grids
- [x] update MOTD and commands
- [x] Enable SEDB Plugin
- [x] remove password
- [x] Back up start save
- [x] Post announcements
- [ ] Update maps and globe
