### ISSUE TITLE
S9 checklist

### ISSUE THREAD

**Issue by Blaylock1988** [GV-Server-Mods/GVK-Settings#325]
- [ ] Add new weapons to block restrictions
- [ ] Add new NPC weapons to block restrictions
- [ ] Add new NPC hovers to block restrictions
- [ ] record test players
- [ ] merge S7 branches into main and republish
- [ ] Reset Voxels
- [ ] faction clean
- [ ] Clear known steam IDs
- [ ] Purge players in SE/identity clean
- [ ] Purge NPC factions
- [ ] Delete Grid Backups
- [ ] Delete Hangar
- [ ] Delete Faction Hangar Storage
- [ ] Delete MES sbcb5 files
- [ ] Clear server logs
- [ ] Clear clear mod content logs
- [ ] Set up Safezones
- [ ] Set MES bools to false
- [ ] Clear and respawn all NPC grids
- [ ] update MOTD and commands
- [ ] Enable SEDB Plugin
- [ ] remove password
- [ ] Back up start save
- [ ] Post announcements
- [ ] Update maps and globe

**Comment by Blaylock1988** [comment]
Mods published
- Drill Blocker
- HoverEngines
- Relative Rotation
-
